
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia/
    username: marcos
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernati.format_sql: true